from __future__ import annotations

ESCALA_LIKERT = {
    1: "Discordo totalmente",
    2: "Discordo",
    3: "Discordo parcialmente",
    4: "Concordo parcialmente",
    5: "Concordo",
    6: "Concordo totalmente",
    7: "Não sei responder",
    8: "Não se aplica",
}

ROTULOS_QE = {
    "QE_I20": "Foram oferecidas oportunidades para os estudantes participarem de programas, projetos ou atividades de extensão universitária.",
    "QE_I21": "Foram oferecidas oportunidades para os estudantes participarem de projetos de iniciação científica e/ou de atividades que estimularam a investigação acadêmica.",
    "QE_I22": "As atividades realizadas durante seu trabalho de conclusão de curso contribuíram para qualificar sua formação profissional.",
    "QE_I23": "As relações professor-aluno ao longo do curso foram positivas, estimulando os estudantes a estudar e aprender.",
    "QE_I24": "Os professores apresentaram e discutiram os planos de ensino/curso das disciplinas com os estudantes.",
    "QE_I25": "As referências bibliográficas indicadas pelos professores contribuíram para seus estudos e aprendizagens.",
    "QE_I26": "As avaliações da aprendizagem realizadas durante o curso foram compatíveis com os conteúdos ou temas trabalhados pelos professores.",
    "QE_I27": "Os professores demonstraram domínio dos conteúdos abordados nas disciplinas.",
    "QE_I28": "Os professores utilizaram estratégias e instrumentos de avaliação diversificados (provas, seminários, trabalhos em grupo, portfólio, autoavaliação, etc.).",
    "QE_I29": "Os professores ofereceram devolutivas das avaliações (comentários, explicações, sugestões para melhoria) que auxiliaram os estudantes a avançar em suas aprendizagens.",
    "QE_I30": "Os professores estimularam a participação ativa dos estudantes durante as aulas, não se limitando às aulas expositivas.",
    "QE_I31": "O curso disponibilizou quantidade suficiente de professores ou tutores para auxiliar os estudantes nas disciplinas a distância.",
    "QE_I32": "Nas disciplinas a distância, houve interação ao vivo entre os estudantes e o professor.",
    "QE_I33": "Foram oferecidas oportunidades para os estudantes superarem dificuldades relacionadas ao processo de formação.",
    "QE_I34": "A coordenação do curso esteve disponível para orientação acadêmica dos estudantes.",
    "QE_I35": "O curso favoreceu a articulação do conhecimento teórico com atividades práticas.",
    "QE_I36": "O curso propiciou acesso a conhecimentos atualizados e/ou contemporâneos em sua área de formação.",
    "QE_I37": "As disciplinas cursadas contribuíram para sua formação como profissional.",
    "QE_I38": "As metodologias de ensino utilizadas no curso desafiaram você a se posicionar mais criticamente diante do conhecimento.",
    "QE_I39": "Os estudantes participaram de avaliações periódicas das condições de formação.",
    "QE_I40": "O Ambiente Virtual de Aprendizagem apresentou materiais, recursos e tecnologias apropriados para o desenvolvimento das disciplinas.",
    "QE_I41": "O curso proporcionou condições de acesso adequado às bibliografias indicadas nas disciplinas, de forma física ou virtual.",
    "QE_I42": "As salas de aula apresentaram tamanho, mobiliário e recursos tecnológicos adequados.",
    "QE_I43": "As condições de infraestrutura dos polos foram adequadas para os encontros presenciais (não se aplica para cursos presenciais).",
    "QE_I44": "Os ambientes e equipamentos destinados às aulas práticas foram adequados ao curso e à quantidade de estudantes.",
    "QE_I45": "Os ambientes e equipamentos destinados às aulas práticas foram adequados ao curso e à quantidade de estudantes.",
    "QE_I46": "Planejar o ensino considerando a proposta curricular, os conhecimentos prévios, as origens culturais, as experiências de vida e os interesses de todos os estudantes.",
    "QE_I47": "Propor objetivos de aprendizagem desafiadores aos estudantes, considerando os diferentes níveis cognitivos e dimensões do conhecimento.",
    "QE_I48": "Planejar sequências didáticas, articulando diferentes estratégias de ensino, recursos e formas de avaliação coerentes com os objetivos de aprendizagem e objetos de conhecimento.",
    "QE_I49": "Utilizar estratégias e recursos diversificados das Tecnologias da Informação e Comunicação, de maneira apropriada e contextualizada ao processo de ensino e aprendizagem.",
    "QE_I50": "Dominar os conhecimentos específicos da minha área de formação e saber como ensiná-los.",
    "QE_I51": "Analisar como os estudantes aprendem, em cada faixa etária e etapa de ensino, utilizando estratégias, recursos e materiais adequados e contextualizados.",
    "QE_I52": "Utilizar diferentes estratégias e recursos para a aprendizagem dos estudantes do público da educação especial.",
    "QE_I53": "Dominar as informações sobre a estrutura e organização do sistema educacional brasileiro, incluindo suas etapas, modalidades e políticas.",
    "QE_I54": "Conhecer o aluno surdo, sua cultura, identidade e utilizar os princípios básicos da Língua Brasileira de Sinais (LIBRAS).",
    "QE_I55": "Trabalhar com o tema das relações étnico-raciais e o ensino de história e cultura afro-brasileira, africana e indígena.",
    "QE_I56": "Realizar a gestão da sala de aula, considerando organização de espaços físicos, tempo, materiais e recursos pedagógicos.",
    "QE_I57": "Identificar e desenvolver estratégias pedagógicas preventivas e corretivas para lidar com indisciplina, bullying e diferentes formas de violência escolar.",
    "QE_I58": "Desenvolver estratégias de gestão de sala de aula que mantenham os alunos interessados e engajados, criando ambiente seguro, organizado e respeitoso.",
    "QE_I59": "Monitorar o processo de aprendizagem dos estudantes, por meio de diferentes estratégias, para identificar avanços e necessidades.",
    "QE_I60": "Utilizar estratégias e instrumentos de avaliação diversificados, considerando a heterogeneidade dos estudantes.",
    "QE_I61": "Oferecer devolutivas das avaliações compreensíveis aos estudantes, com comentários, explicações e sugestões.",
    "QE_I62": "Dominar as informações sobre as avaliações externas, sabendo integrá-las ao planejamento das ações didático-pedagógicas da escola.",
    "QE_I63": "Trabalhar em equipe dialogando sobre minhas práticas pedagógicas, de modo colaborativo e solidário.",
    "QE_I64": "Refletir permanentemente sobre a minha prática pedagógica, revisando-a e readequando-a sempre que necessário.",
    "QE_I65": "Reconhecer a importância de participar da comunidade escolar de maneira propositiva, respeitando decisões colegiadas e colaborando para a melhoria da escola.",
    "QE_I66": "Interagir com as famílias, respeitando as suas culturas e múltiplas formas de organização, visando a melhoria da aprendizagem.",
    "QE_I68": "Em uma escala de 0 a 10, o quanto você recomendaria o seu curso para um amigo ou colega?",
    "QE_I69": "Em uma escala de 0 a 10, o quanto você recomendaria a sua Instituição de Educação Superior para um amigo ou colega?",
    "QE_I70": "Qual o seu interesse em participar da Prova Nacional Docente – 2025?",
}

DIMENSOES_TEORICAS = {
    "oportunidades_formacao": ("QE_I20", "QE_I21", "QE_I22", "QE_I33"),
    "atuacao_docente": tuple(f"QE_I{i}" for i in range(23, 31)),
    "organizacao_integracao": tuple(f"QE_I{i}" for i in range(34, 40)),
    # QE_I43 é específico de polos/EaD e não integra a dimensão comum.
    "infraestrutura_recursos": ("QE_I40", "QE_I41", "QE_I42", "QE_I44", "QE_I45"),
    "planejamento_ensino": tuple(f"QE_I{i}" for i in range(46, 52)),
    "inclusao_diversidade": tuple(f"QE_I{i}" for i in range(52, 56)),
    "gestao_avaliacao": tuple(f"QE_I{i}" for i in range(56, 63)),
    "colaboracao_escola_familia": tuple(f"QE_I{i}" for i in range(63, 67)),
}

ROTULOS_DIMENSOES = {
    "oportunidades_formacao": "Oportunidades de formação",
    "atuacao_docente": "Atuação docente",
    "organizacao_integracao": "Organização e integração teoria-prática",
    "infraestrutura_recursos": "Infraestrutura e recursos",
    "planejamento_ensino": "Preparação para planejamento e ensino",
    "inclusao_diversidade": "Inclusão e diversidade",
    "gestao_avaliacao": "Gestão da sala e avaliação",
    "colaboracao_escola_familia": "Colaboração, escola e famílias",
}

ITENS_INVERTIDOS: tuple[str, ...] = ()
